---
# Ansible Playbook for some configration on debian based distros
# Replace "{{user_name}}" with your username in following format:
# username: exampleuser
- name: Configure Linux via Playbook
  hosts: localhost
  vars:
    state: latest
    username: "{{user_name}}"

  tasks:
    - name: Upgrade all apt packages
      apt:
        force_apt_get: yes
        upgrade: dist
      become: yes

    - name: Install screen via apt
      apt:
        name: screen
        state: present
      become: yes

    - name: Install vim via apt
      apt:
        name: vim
        state: present
      become: yes

    - name: Install btop via apt
      apt:
        name: apt
        state: present
      become: yes

    - name: Install rsync via apt
      apt:
        name: rsync
        state: present
      become: yes

    - name: Install unzip via apt
      apt:
        name: unzip
        state: present
      become: yes

    - name: Install wireshark (wireshark-qt) via apt
      apt:
        name: wireshark-qt
        state: present
      become: yes

    - name: Install neofetch via apt
      apt:
        name: neofetch
        state: present
      become: yes

    - name: Install hollywood via apt
      apt:
        name: hollywood
        state: present
      become: yes

    - name: Install nala (apt-frontend) via apt
      apt:
        name: nala
        state: present
      become: yes

    - name: Enable Snap (remove nosnap.pref)
      ansible.builtin.file:
        path: /etc/apt/preferences.d/nosnap.pref
        state: absent
      become: yes

    - name: Remove Password requirement for sudo group members in sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo  ALL='
        line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
      become: yes

    - name: Remove LibreOffice (if present) using apt
      ansible.builtin.apt:
        name: libreoffice-*
        state: absent
      become: yes

    - name: Add SSH key to authorized keys
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "ssh-rsa key goes here"
